### ISSUE TITLE
Check on UDP length maybe discards correct responses

### ISSUE THREAD

**Issue by FStefanni** [khoih-prog/MDNS_Generic#10]
### Describe the bug

Hi,

I have this setup:
* a Linux laptop
* a Raspberry
* a Esp32

On all of tem MDNS is configured (on Esp32, I am using the example sketch `WiFiResolvingHostNames`)
* Linux and Raspberry are able to see each others (ping, ssh and avahi-resolve work fine).
* Linux and Raspberry are able to resolve the Esp32 ip (ping and avahi-resolve).
* Esp32 is unable to resolve Linux or Raspberry ips.

After some debug, I have found this check in the lib code (near line 963 of file `MDNS_Generic_Impl.h`):
```c++
//KH, to report name Resolve only UDP packet has corect size of 48
if (48 == udp_len)
```
So I put a debug print, and actually what I got is:
* `udp_len` equals to 40
* The data pointed by `buf` actually contains the correct ip.

So the question/bug is:
* Why consider only length of 48? Is truly incorrect checking also for different lengths (as in my case for 40)?
* If the length of 48 is the only correct, then why the example sketch is unable to resolve the ip? What am I doing wrongly? 

Please note that on Rasberry and Linux no acutal services discoverable via MDNS are running: what I need is to just resolve the ip.

Regards

### Steps to Reproduce

I am using the `WiFiResolvingHostNames` sketch.

### Expected behavior

I was expecting to be able to resolve the ip.

### Actual behavior

The sketch prints `Resolving XXX error`

### Information

* Arduino IDE version: 1.8.19
* `ESP32` Arduino library version: 2.0.3

**Comment by khoih-prog** [comment]
Hi @FStefanni 

Thanks for your usage of the library and the issue report.

As you're using ESP32, I suggest that you use the native ESP32-core [**ESPmDNS** library](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESPmDNS)

If you still have issue, please post on the ESP32 core issue, with the [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example) so that other people can duplicate the issue and help.

I'm sorry I don't have time to spend here as the library is mainly designed for boards besides ESP32/ESP8266, and I'm trying to offload any issue to other cores / libraries if possible.

I certainly reopen, spend some time to investigate and fix the library if you can prove clearly this is a bug of the library.

Thanks again and Good Luck,

**Comment by FStefanni** [comment]
Hi,

thank you for the reply.
So my doubt is: is it really correct to check only for a length of 48? Why am I receiving a length of 40?

Nevertheless, I am going to check the [ESPmDNS library](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESPmDNS) library.

Regards
